#!/bin/bash
# =============================================================================
# Optimal Scanner Agent - Quick Install Script
# =============================================================================
#
# Works with any self-hosted Optimal Platform deployment.
#
# Usage:
#   curl -sSL $YOUR_PLATFORM_URL/install/scanner.sh | bash -s -- YOUR_API_TOKEN YOUR_API_URL
#
# Or with environment variables:
#   export OPTIMAL_API_TOKEN=your-token
#   export OPTIMAL_API_URL=https://api.your-platform.com
#   ./install.sh
#
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Configuration - supports both positional args and environment variables
API_TOKEN="${1:-${OPTIMAL_API_TOKEN:-}}"
API_URL="${2:-${OPTIMAL_API_URL:-}}"
INSTALL_DIR="${INSTALL_DIR:-/usr/local/bin}"
SCANNER_IMAGE="${OPTIMAL_SCANNER_IMAGE:-optimal/scanner:latest}"

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║             Optimal Scanner Agent - Quick Install                 ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check for API token
if [ -z "$API_TOKEN" ]; then
    echo -e "${RED}Error: API token required${NC}"
    echo ""
    echo "Usage: $0 <API_TOKEN> <API_URL>"
    echo ""
    echo "Or set environment variables:"
    echo "  export OPTIMAL_API_TOKEN=your-token"
    echo "  export OPTIMAL_API_URL=https://api.your-platform.com"
    echo ""
    echo "Get your API token from your platform's settings page."
    exit 1
fi

# Check for API URL
if [ -z "$API_URL" ]; then
    echo -e "${RED}Error: API URL required${NC}"
    echo ""
    echo "Usage: $0 <API_TOKEN> <API_URL>"
    echo ""
    echo "Or set environment variables:"
    echo "  export OPTIMAL_API_URL=https://api.your-platform.com"
    exit 1
fi

# Detect OS
OS="$(uname -s)"
ARCH="$(uname -m)"

echo -e "${BLUE}Configuration:${NC}"
echo "  API URL: $API_URL"
echo "  OS: $OS $ARCH"
echo ""

# Check for Docker
if command -v docker &> /dev/null; then
    echo -e "${GREEN}✓${NC} Docker detected"
    INSTALL_METHOD="docker"
else
    echo -e "${YELLOW}!${NC} Docker not found, installing Python version"
    INSTALL_METHOD="python"
fi

# Install based on method
if [ "$INSTALL_METHOD" = "docker" ]; then
    echo ""
    echo -e "${BLUE}Installing Docker-based scanner...${NC}"

    # Pull the scanner image
    echo "Pulling scanner image..."
    docker pull $SCANNER_IMAGE 2>/dev/null || {
        echo -e "${YELLOW}Could not pull from registry, building locally...${NC}"
        # Build locally if pull fails (for development/air-gapped environments)
        SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        if [ -f "$SCRIPT_DIR/Dockerfile" ]; then
            docker build -t $SCANNER_IMAGE "$SCRIPT_DIR"
        else
            echo -e "${RED}Error: Could not install scanner${NC}"
            echo "For air-gapped environments, ensure the scanner image is available locally."
            exit 1
        fi
    }

    # Create wrapper script
    echo "Creating wrapper script..."
    cat > /tmp/optimal-scan << EOF
#!/bin/bash
# Optimal Scanner Agent wrapper
# Auto-generated by install script

export OPTIMAL_API_URL="${API_URL}"
export OPTIMAL_API_TOKEN="${API_TOKEN}"

docker run --rm \\
    -v /var/run/docker.sock:/var/run/docker.sock \\
    -e OPTIMAL_API_URL="\${OPTIMAL_API_URL}" \\
    -e OPTIMAL_API_TOKEN="\${OPTIMAL_API_TOKEN}" \\
    $SCANNER_IMAGE \\
    --api-url "\${OPTIMAL_API_URL}" \\
    --token "\${OPTIMAL_API_TOKEN}" \\
    "\$@"
EOF

    # Install wrapper
    if [ -w "$INSTALL_DIR" ]; then
        mv /tmp/optimal-scan "$INSTALL_DIR/optimal-scan"
        chmod +x "$INSTALL_DIR/optimal-scan"
    else
        echo -e "${YELLOW}Need sudo to install to $INSTALL_DIR${NC}"
        sudo mv /tmp/optimal-scan "$INSTALL_DIR/optimal-scan"
        sudo chmod +x "$INSTALL_DIR/optimal-scan"
    fi

else
    echo ""
    echo -e "${BLUE}Installing Python-based scanner...${NC}"

    # Check Python
    if ! command -v python3 &> /dev/null; then
        echo -e "${RED}Error: Python 3 required${NC}"
        exit 1
    fi

    # Install dependencies
    pip3 install --user aiohttp docker pyyaml 2>/dev/null || pip3 install aiohttp docker pyyaml

    # Try to download scanner from platform
    echo "Downloading scanner from platform..."
    SCANNER_DOWNLOAD_URL="${API_URL}/install/scanner.py"

    if command -v curl &> /dev/null; then
        curl -sSL -o /tmp/scanner.py "$SCANNER_DOWNLOAD_URL" 2>/dev/null || {
            echo -e "${YELLOW}Could not download from platform, checking local copy...${NC}"
            SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
            if [ -f "$SCRIPT_DIR/scanner.py" ]; then
                cp "$SCRIPT_DIR/scanner.py" /tmp/scanner.py
            else
                echo -e "${RED}Error: Could not obtain scanner script${NC}"
                exit 1
            fi
        }
    fi

    # Create wrapper script
    cat > /tmp/optimal-scan << EOF
#!/bin/bash
# Optimal Scanner Agent wrapper
# Auto-generated by install script

export OPTIMAL_API_URL="${API_URL}"
export OPTIMAL_API_TOKEN="${API_TOKEN}"

python3 /usr/local/share/optimal-scanner/scanner.py \\
    --api-url "\${OPTIMAL_API_URL}" \\
    --token "\${OPTIMAL_API_TOKEN}" \\
    "\$@"
EOF

    # Install
    if [ -w "$INSTALL_DIR" ]; then
        mkdir -p /usr/local/share/optimal-scanner
        cp /tmp/scanner.py /usr/local/share/optimal-scanner/ 2>/dev/null || true
        mv /tmp/optimal-scan "$INSTALL_DIR/optimal-scan"
        chmod +x "$INSTALL_DIR/optimal-scan"
    else
        echo -e "${YELLOW}Need sudo to install to $INSTALL_DIR${NC}"
        sudo mkdir -p /usr/local/share/optimal-scanner
        sudo cp /tmp/scanner.py /usr/local/share/optimal-scanner/ 2>/dev/null || true
        sudo mv /tmp/optimal-scan "$INSTALL_DIR/optimal-scan"
        sudo chmod +x "$INSTALL_DIR/optimal-scan"
    fi
fi

# Verify installation
echo ""
if command -v optimal-scan &> /dev/null; then
    echo -e "${GREEN}✓ Installation complete!${NC}"
    echo ""
    echo -e "${CYAN}Quick Start:${NC}"
    echo ""
    echo "  # Scan a container image"
    echo "  optimal-scan --image nginx:latest"
    echo ""
    echo "  # Scan all running containers"
    echo "  optimal-scan --all-containers"
    echo ""
    echo "  # Scan a directory"
    echo "  optimal-scan --path /app"
    echo ""
    echo "  # Run in daemon mode (continuous scanning)"
    echo "  optimal-scan --daemon --interval 300"
    echo ""
    echo -e "${CYAN}Configuration:${NC}"
    echo "  API URL: $API_URL"
    echo "  Results will appear in your platform dashboard."
else
    echo -e "${RED}Installation may have failed. Please check the output above.${NC}"
    exit 1
fi

# Test connection
echo ""
echo -e "${BLUE}Testing connection to Optimal Platform...${NC}"
optimal-scan --image alpine:latest 2>/dev/null && {
    echo -e "${GREEN}✓ Connection successful!${NC}"
} || {
    echo -e "${YELLOW}! Could not verify connection (this may be normal for demo mode)${NC}"
}

echo ""
echo -e "${GREEN}Scanner installed successfully!${NC}"
