{{- if and .Values.platform.apiKey (not .Values.platform.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "optimal-agent.fullname" . }}-credentials
  labels:
    {{- include "optimal-agent.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.platform.apiKey | b64enc }}
{{- end }}
